name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: "Version to deploy"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  actions: write
  contents: read

jobs:
  saga:
    runs-on: ubuntu-latest

    environment: production

    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      STACK_PREFIX: ${{ vars.STACK_PREFIX }}
      HOSTING_STACK_NAME: ${{ vars.STACK_PREFIX }}-hosting
      COGNITO_USER_POOL_CLIENT_ID: ${{ vars.COGNITO_USER_POOL_CLIENT_ID }}
      COGNITO_USER_POOL_URL: ${{ vars.COGNITO_USER_POOL_URL }}
      COGNITO_IDENTITY_POOL_ID: ${{ vars.COGNITO_IDENTITY_POOL_ID }}

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Determine released version
        id: version
        run: |
          git fetch --tags
          VERSION=`git describe --abbrev=0 --tags --always | tr -d '\n'`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: |
          npm run build
          cp -L -r ./static ./build
          mkdir -p build/node_modules/bootstrap/dist/css/
          cp node_modules/bootstrap/dist/css/bootstrap.css build/node_modules/bootstrap/dist/css/
          mkdir  ./build/.well-known
          echo ${{ steps.version.outputs.version }} > ./build/.well-known/release

      - name: Cache AWS CLI (Linux)
        id: cache-aws-cli
        uses: actions/cache@v4
        with:
          path: aws/
          key: cache-aws-cli

      - name: Install AWS
        if: steps.cache-aws-cli.outputs.cache-hit != 'true'
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: |-
            arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.HOSTING_STACK_NAME }}-web-app-cd
          role-session-name: gh-actions-publish
          aws-region: ${{ env.AWS_REGION }}

      - name: Get bucket name
        run: |-
          BUCKET_NAME=`aws cloudformation describe-stacks --stack-name ${{ env.HOSTING_STACK_NAME }} | jq -r '.Stacks[0].Outputs[] | select(.OutputKey == "bucketName") | .OutputValue'`
          echo $BUCKET_NAME
          if [ -z "${BUCKET_NAME}" ]; then
            echo "BUCKET_NAME is empty."
            exit 1
          fi
          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV

      - name: Remove old files
        run: |
          aws s3 rm s3://${{ env.BUCKET_NAME }} --recursive

      - name: Upload build
        run: |
          aws s3 sync build s3://${{ env.BUCKET_NAME }}

      - name: Set cache metadata
        run: |
          # All files to 1 year
          aws s3 cp s3://${{ env.BUCKET_NAME }} s3://${{ env.BUCKET_NAME }} --recursive --cache-control max-age=30758400,public
          # HTML files and .well-known/ to 10 minutes
          aws s3 cp s3://${{ env.BUCKET_NAME }} s3://${{ env.BUCKET_NAME }} --exclude "*" --include "*.html" --include ".well-known/*" --recursive --cache-control max-age=600,public --content-type "text/html; charset=UTF-8"

      - name:
          Trigger CloudFront cache invalidation for fixed resources (all other
          files have unique names)
        run: |
          node --no-warnings --experimental-transform-types .github/workflows/invalidate-cloudfront.ts
